### ISSUE TITLE
Exporting configuration: unhandled exception

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [builtbybel/xd-AntiSpy#13]
![image](https://github.com/builtbybel/xd-AntiSpy/assets/47056543/62f232ab-87a1-453b-b198-62d365f5c4a7)

I had the same problem when I selected the delightfully entitled 'search for crappy apps'.

Still: I had those problems when, and only when, I ran the program directly from the zip.

xd-AntiSpy 4.06
Windows 10 Pro - 22H2 (2009: 19045)

**Comment by Belim** [comment]
Yeah, that's normal! Apps need to be extracted from ZIPs to run properly, especially with dependencies like Newtonsoft.Json

**Comment by LinuxOnTheDesktop** [comment]
Yet, with some apps one can get away with it. So, a note in the README?

**Comment by Belim** [comment]
That makes sense, yeah
