### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by Tumbleweed64** [builtbybel/xd-AntiSpy#38]
Windows 11 23H2, German
xd-AntiSpy v4.11.10

When trying to load from Tools the Debloater or Butler i get these errors:

`Error loading Plugin from PluginDebloater.dll: Die Datei oder Assembly “file:///D:Portables\xd-AntiSpy\plugins\PluginDebloater.dll” oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)`

`Error loading Plugin from PluginButler.dll: Die Datei oder Assembly “file:///D:Portables\xd-AntiSpy\plugins\PluginButler.dll” oder eine Abhängigkeit davon wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESULT: 0x80131515)`

Zip is unpacked, i'm starting xd-AntiSpy.exe from D:\Portables\xd-AntiSpy

**Comment by Belim** [comment]
I can't understand or reproduce the problem at all. It looks like the plugins folder might be missing. Please download the complete package and extract it to the desired external drive. Does the error message really include that before 'file:///'?

**Comment by Tumbleweed64** [comment]
Hi, thanks for your response.

D: is an internal local data ssd where i store apps for use on usb. So i can test before i copy to usb.
Yes, all files are complete, inluded plugins dir and plugins files. I've checked this several times before posting here, i've also tried new downloads and testing again before posting.
Yes, the error message include 'file:///'

Two screenshots, hope this helps:
![xd-antispy-butler](https://github.com/user-attachments/assets/7e8dae0c-0699-42c9-86bf-c8b4750ac1f4)
![xd-antispy-debloater](https://github.com/user-attachments/assets/69abe21e-9542-4202-b910-f33f4d742263)

**Comment by Belim** [comment]
Could it be that Windows might be blocking the DLLs? Try unblocking them in the properties. Right-click on the DLL, go to the bottom of the security tab, and click unlock if it's locked. Does this only happen on the USB stick?

**Comment by Belim** [comment]
Can you please test both dev versions and let me know which ones work
[dev1.zip](https://github.com/user-attachments/files/16444649/dev1.zip)
[dev2.zip](https://github.com/user-attachments/files/16444650/dev2.zip)

**Comment by onxzy** [comment]
Hello, I faced the same issue. 

> Could it be that Windows might be blocking the DLLs? Try unblocking them in the properties. Right-click on the DLL, go to the bottom of the security tab, and click unlock if it's locked. Does this only happen on the USB stick?

This solved issue for me.

I also tried your dev versions and versions 1 and 4f are working (without unlocking the DLL in its settings) but not versions 2 and 3.  

However it seems that I face this issue only if I extract the .zip using this windows explorer unzip feature, if I unzip it with 7zip it works as expected (for current release as well as dev versions 2 and 3). Extracting with the explorer also shows the Microsoft Defender SmartScreen on first launch while extracting with 7zip doesn't.

**Comment by Tumbleweed64** [comment]
> However it seems that I face this issue only if I extract the .zip using this windows explorer unzip feature, if I unzip it with 7zip it works as expected (for current release as well as dev versions 2 and 3). Extracting with the explorer also shows the Microsoft Defender SmartScreen on first launch while extracting with 7zip doesn't.

Thats it! Thanks! :-)
Have tried like you with windows explorer to unpack and got errors with all versions, dev1-4. Than i use 7zip and all works, without any errors.

@Belim, thanks for your tool, your work and sorry for the confusion. :-)

**Comment by Belim** [comment]
@Tumbleweed64 Awesome, thanks for the wonderful large coffee 😃
