### ISSUE TITLE
Perfect App

### ISSUE THREAD

**Issue by odorizzioficial** [builtbybel/xd-AntiSpy#4]
Your program is really cool, friend, but could you bring the Brazilian Portuguese language to the app, that would help a lot, hugs

**Comment by Belim** [comment]
With a larger user base, I will provide localization options. Currently, it is still a small side project

**Comment by Mira-Bellenbaum** [comment]
Hi Belim, Du könntest aber auch die Resource der "Texte" auslagern, z.B. in eine LNG-Datei, dann könnte, wer es denn möchte,
diese originale, in englisch verfasste Texte übersetzen und wenn Du es denn anbieten würdest, diese anderen Sprachversionen zur Verfügung stellen. Musst doch nicht alles alleine machen!
Gäbe ja auch noch eine andere Möglichkeit, aber die hast Du aber leider verbaut!
Denn mit dem ResouceHacker bekomme ich weder in der EXE noch in der Dll zugriff auf die Recoucen.
Auch so könnte man, zumindest privat, sich seine sprach angepasste Version erschaffen.
Wie gesagt (geschrieben), Du musst nicht alles alleine machen.

**Comment by Belim** [comment]
Moin Mira, ich erinnere mich, dass es beim alten Kunden eine deutsche Resourcedatei gab, als die App noch in C++ geschrieben war. Ich werde diesbezüglich mal nachfragen. Falls das nicht klappt, werde ich sie mal neu Lokalisieren (den Code muss ich sowieso neu schreiben) . Die Pflege der deutschen Übersetzung würde ich allerdings gerne abgeben. Ich melde mich.

**Comment by Mira-Bellenbaum** [comment]
Cool, erwarte Deine Antwort. 
Wenn möglich per E-Mail, mira[.]bellenbaum(at)gmx[.]net

Ansonsten muss ich halt öfter hier vorbeischauen, was jetzt auch nicht so dramatisch ist,
aber auf die E-Mail würde ich halt schneller reagieren.

**Comment by odorizzioficial** [comment]
I have a YouTube channel, can I show your app to my audience?

**Comment by odorizzioficial** [comment]
And another, is this a virus?
![image](https://github.com/builtbybel/xd-AntiSpy/assets/110546717/090f5a6d-6452-47c9-858c-c9e699a0dee9)

**Comment by Belim** [comment]
> I have a YouTube channel, can I show your app to my audience?

Sure thing, I'm actually all for it. Thanks! 😺

**Comment by Belim** [comment]
> And another, is this a virus? ![image](https://private-user-images.githubusercontent.com/110546717/345830607-090f5a6d-6452-47c9-858c-c9e699a0dee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDA4ODUsIm5iZiI6MTcyMDEwMDU4NSwicGF0aCI6Ii8xMTA1NDY3MTcvMzQ1ODMwNjA3LTA5MGY1YTZkLTY0NTItNDdjOS04NThjLWM5ZTY5OWEwZGVlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxMzQzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjBkZWU5ZTg1ZGM4MDE5MmRmMGYxODNmZTE2NDdhYjVlNmNmMGQ0ZmNiNWY4ZjA1NGQ3NzQ0NDIyYmMwZjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y6RZGPgCOwpjiRxPrJtsGx0X7IM7NFtwPyrERAau-F8)

Nope, that's a false positive from some unknown garbage AV engine nobody knows. No worries!

**Comment by tGecko** [comment]
Where's the source code?
