### ISSUE TITLE
NewTabPageHideDefaultTopSites false value requested.

### ISSUE THREAD

**Issue by rsoyxihnark** [builtbybel/xd-AntiSpy#50]
NewTabPageHideDefaultTopSites

program sets this value to 0 to disable tracking.

correct value would be 1, source:
https://admx.help/?Category=EdgeChromium&Policy=Microsoft.Policies.Edge::NewTabPageHideDefaultTopSites

**Comment by Belim** [comment]
Thanks  😃 and fixed https://github.com/builtbybel/xd-AntiSpy/releases/tag/4.11.100
