### ISSUE TITLE
DisableSearchBoxSuggestions wrong path requested.

### ISSUE THREAD

**Issue by rsoyxihnark** [builtbybel/xd-AntiSpy#51]
program targets DisableSearchBoxSuggestions value in the path of:
HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows

correct value would be:
HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Explorer

I assume it's a typo.

**Comment by Belim** [comment]
Thanks  😃 and fixed https://github.com/builtbybel/xd-AntiSpy/releases/tag/4.11.100
