### ISSUE TITLE
I have created a Simplified Chinese language pack (zh-has, chinese)， please include it in the software.

### ISSUE THREAD

**Issue by fsjoy52** [builtbybel/xd-AntiSpy#58]
This is a great software. Thank you for your ongoing development.

I have created a Simplified Chinese language pack (zh-has, chinese) using the steps you described.

Best regards.
[zh-hans chinese.zip](https://github.com/user-attachments/files/16638980/zh-hans.chinese.zip)

**Comment by Belim** [comment]
I was unsure about the long code, but it should be correct based on my research
  zh-hans (simplified Chinese characters)
  zh-hant (traditional Chinese characters)
  zh-cn (Chinese language variant, uses simplified characters)
  zh-tw (Taiwanese language variant, uses traditional characters) 
https://h5p.org/node/1148398

I have enabled the language pack. Could you please check if it's being offered for download? Thank you very much for your work

**Comment by fsjoy52** [comment]
Hello, the language pack is now available for download. You can choose the zh-cn option (Chinese language variant, uses simplified characters).
