### ISSUE TITLE
More of a question than an issue (I think)

### ISSUE THREAD

**Issue by hbrof** [builtbybel/xd-AntiSpy#60]
When you first run the program, some of the items are checked, others are not. Is this what is going to happen or the settings as they already exist? 

If the changes are made, is running the application again and doing the opposite fully setting it back or no?

I ask this because I am not sure I want so many changes to be made, I'd like to make smaller numbers of changes at a time since it's not clear what the various settings actually refer to and if I guess wrong, I want to be able to set them back until I find the one that fits what I am looking for.

thanks

**Comment by Belim** [comment]
I always assumed it was self-explanatory. Maybe I should offer a small intro when the app starts. You can get more info by using the F1 shortcut. At the start of the app, your system is analyzed, and settings are automatically detected. If a checkbox is checked, it means that the setting is already active (either by default or enabled by you). Activating or deactivating individual options won’t apply any changes immediately. Only when you click the "Apply" button will the settings be enabled or disabled according to your selections

**Comment by Belim** [comment]
> If the changes are made, is running the application again and doing the opposite fully setting it back or no?

You check a box and click Apply. The settings are applied. You uncheck a box and click Apply. It’s that simple ;)

**Comment by hbrof** [comment]
Ok, thank you. it is what I presumed. So the other clarification based on these two answers is, if a box doesn't change, ie: checked to unchecked or unchecked to checked, is that setting left alone, or does clicking "Apply" apply all settings as checked or just those that have been changed?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Belim** [comment]
> if a box doesn't change, ie: checked to unchecked or unchecked to checked, is that setting left alone, or does clicking "Apply" apply all settings as checked or just those that have been changed?

 Only the latest changes are applied. You can apply multiple changes at once by adjusting several checkbox statuses and hitting "Apply." Your settings from a previous session remain unchanged as long as you don't mess with the checkboxes here. In a session, practically everything you check or uncheck and then apply gets changed. Anything you don't touch (by checking or unchecking a box) won't be applied when you click "Apply." ;)

**Comment by hbrof** [comment]
Excellent. I would note that when running. It is why I had not actually Applied any changes yet when I asked. If you don't mind a few other constructive considerations. 1) Since the refresh button clears any clicks a user has pending, a warning that they will be lost when clicking is a good idea. 2) When a change is made, perhaps a different color on that item would be helpful to the user as they scroll up and down through the various settings. 3) when any change is made, perhaps highlight that Apply button so the user knows there are changes pending and are ready to Apply.

**Comment by hbrof** [comment]
One other quick set of questions, probably relevant to anyone who's done the latest Windows update (August). Are any of the settings related to turning off the 3 items circled?
![task bar w icon examples](https://github.com/user-attachments/assets/a95d7319-fa99-4c8e-a852-b123239cfa08)

**Comment by Belim** [comment]
1) doesn’t make much sense to me
2 This has always been the case, yellow color 
3) All changes will be highlighted in yellow when the Apply button is clicked

Regarding your image, you just need to disable Widgets, the Search Box, and Copilot in the app. All options are supported

**Comment by hbrof** [comment]
Thanks Again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
