### ISSUE TITLE
Polish translation for xd-AntiSpy

### ISSUE THREAD

**Issue by RavJ81** [builtbybel/xd-AntiSpy#62]
[Export.zip](https://github.com/user-attachments/files/16673913/Export.zip)

**Comment by Belim** [comment]
Added . Many thanks 😸

**Comment by RavJ81** [comment]
Can I enter my translator's details in the translation file?

**Comment by Belim** [comment]
Yes, please :)

**Comment by RavJ81** [comment]
New polish translation.
[Export.zip](https://github.com/user-attachments/files/16933226/Export.zip)

**Comment by RavJ81** [comment]
Polish translation for xd-AntiSpy v4.13
[Export.zip](https://github.com/user-attachments/files/17078636/Export.zip)
