### ISSUE TITLE
windows display scaling

### ISSUE THREAD

**Issue by whitelightning76** [builtbybel/xd-AntiSpy#8]
Windows display scaling seems to be broken with this release.  

Can you please take a look at this ?

![image](https://github.com/builtbybel/xd-AntiSpy/assets/16383535/01708ab4-fb30-4e30-827d-efdda84b6640)

**Comment by Belim** [comment]
I scaled it to 175% here and it’s working perfectly. Could you check out today’s release https://github.com/builtbybel/xd-AntiSpy/releases/tag/4.0.5?

**Comment by whitelightning76** [comment]
I have tried the new version and I get the same result as my first post.  I have no idea why my system puts it like that and your version is fine.   I

**Comment by Belim** [comment]
also try it with a different user profile, if possible. It could also be due to a missing graphics driver.

**Comment by whitelightning76** [comment]
> Have you set a custom scaling, and if so, what is it? Do you use multiple monitors, and perhaps one scales correctly while the other does not? If so, try moving the forms between the monitors and ensure that both have the same scaling set

basicly anything above 200% is unreadable.  I have set mine to 250 (recommended is 300 even).

I so notice that Windows Defender Smartscreen is popping up when I launch it.  Might that be the reason why windows does not scale ?

**Comment by Belim** [comment]
> > Have you set a custom scaling, and if so, what is it? Do you use multiple monitors, and perhaps one scales correctly while the other does not? If so, try moving the forms between the monitors and ensure that both have the same scaling set
> 
> basicly anything above 200% is unreadable. I have set mine to 250 (recommended is 300 even).
> 
> I so notice that Windows Defender Smartscreen is popping up when I launch it. Might that be the reason why windows does not scale ?

found a bug in the .NET Framework! I think this version should fix it. Please give it a try
[xd-AntiSpy4.05-2-dev.zip](https://github.com/user-attachments/files/16112194/xd-AntiSpy4.05-2-dev.zip)

**Comment by whitelightning76** [comment]
Good job!   It is fixed now!
